package api

import (
	s "go-chat/internal/storage"
	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
	
	_ "go-chat/docs" // This will be generated by swag
)

var certFile = "cert.pem"
var keyFile = "key.pem"

func Serve(port string) error {
	r := gin.Default()

	db, err := s.Connect()

	if err != nil {
		panic(err)
	}

	router := NewRouter(db)
	router.RegisterRoutes(r)
	
	// Swagger documentation endpoint
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	return r.RunTLS(port, certFile, keyFile)
}

